#!/usr/bin/python
# update time spent for all tasks
# thomasballinger@gmail.com

import os, sys, optparse

import calendarHours as hours
import spreadsheetTask as task

task_list = task.createTasks()
for task in task_list:
    print 'updating',task.name,task.timespent,
    task.timespent = hours.getHoursWorked(task.id)
    print 'to',task.timespent 
    task.put()
